### ISSUE TITLE
function called in tutorial, not exported in Giotto@suite package

### ISSUE THREAD

**Issue by arschat** [drieslab/Giotto_ReadtheDocs#52]
In the Nanostring CosMx tutorial, the `createGiottoObjectSubcellular` function that is called in cell 3, is not exported from the Giotto@suite that is installed in the beginning.
[docs/source/subsections/datasets/Nanostring_Lung12_jan26_21.rst](https://github.com/drieslab/Giotto_ReadtheDocs/blob/suite/docs/source/subsections/datasets/Nanostring_Lung12_jan26_21.rst#3-create-a-giotto-object-for-each-fov)

Also, there is a typo in the branch name specification in _install_github_ call, in the repo, "suite" has lowercase s.

**Comment by arschat** [comment]
Problem resolved with update of bioconductor from version 3.14 to version 3.16 
`BiocManager::install(version = "3.16")`

and reinstalled Giotto@suite branch 
`devtools::install_github("drieslab/Giotto@suite")`

Thanks for the package!

**Comment by RubD** [comment]
Thanks @arschat for providing feedback and a timely update!
