### ISSUE TITLE
2nd-seq data for Seq-Scope example

### ISSUE THREAD

**Issue by wyq977** [drieslab/Giotto_ReadtheDocs#73]
Hi I would like to reproduce some of the results from Raw data, however, I could
not get the `2nd-seq data` from the example dataset

I only found the fastq files for 1st-seq on https://deepblue.lib.umich.edu/data/concern/data_sets/9c67wn05f
```
DraI-100pM-mbcore-RD2.fastq.gz
>>> 1st-Seq raw MiSeq FASTQ output file for liver dataset
DraI_100pM_RD4.fastq.gz
>>> 1st-Seq raw MiSeq FASTQ output file for colon dataset
```

The GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE169706) only 
provide 
> 1) High definition map coordinate identifier (HDMI) sequence, tile and spatial coordinate information from 1st-Seq, (2) HDMI sequence, coupled with cDNA sequence from 2nd-Seq,

Can you clarify on where the raw data for 2nd-seq is located and 
how to access?

Best

**Comment by JunxiangXu** [comment]
Thanks for catching up. The 2nd seq data for SeqScope can be found at SRA: 
https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRX10457008&o=acc_s%3Aa and 
More specifically, the Giotto SeqScope tutorial(https://giottosuite.readthedocs.io/en/latest/subsections/datasets/seqscope_mouse_liver_221115.html) is generated from sequencing run number SRR14082759.

**Comment by jiajic** [comment]
Closing as completed
